/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobb;

/**
 *
 * @author VIRAJ
 */
public class _P1 extends javax.swing.JFrame {

    /**
     * Creates new form _P1
     */
    public _P1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_metermade = new javax.swing.JButton();
        jButton_metermade1 = new javax.swing.JButton();
        jButton_metermade2 = new javax.swing.JButton();
        jButton_metermade3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 524));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 524));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_metermade.setBackground(new java.awt.Color(204, 204, 204));
        jButton_metermade.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButton_metermade.setText("RECORD");
        jButton_metermade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_metermadeActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_metermade, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 240, -1));

        jButton_metermade1.setBackground(new java.awt.Color(204, 204, 204));
        jButton_metermade1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButton_metermade1.setText("ADD NEW LOT");
        jButton_metermade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_metermade1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_metermade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 240, -1));

        jButton_metermade2.setBackground(new java.awt.Color(204, 204, 204));
        jButton_metermade2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButton_metermade2.setText("CONTINUE LOT");
        jButton_metermade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_metermade2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_metermade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 240, -1));

        jButton_metermade3.setBackground(new java.awt.Color(204, 204, 204));
        jButton_metermade3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButton_metermade3.setText("END GOING LOT ");
        jButton_metermade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_metermade3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_metermade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 240, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_metermadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_metermadeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_metermadeActionPerformed

    private void jButton_metermade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_metermade1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        p2 sp=new p2();
        sp.setVisible(true);
    }//GEN-LAST:event_jButton_metermade1ActionPerformed

    private void jButton_metermade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_metermade2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        p1 sp=new p1();
        sp.setVisible(true);
    }//GEN-LAST:event_jButton_metermade2ActionPerformed

    private void jButton_metermade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_metermade3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        p4 sp=new p4();
        sp.setVisible(true);
    }//GEN-LAST:event_jButton_metermade3ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_P1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_P1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_P1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_P1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _P1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_metermade;
    private javax.swing.JButton jButton_metermade1;
    private javax.swing.JButton jButton_metermade2;
    private javax.swing.JButton jButton_metermade3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
