/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VIRAJ
 */
public class p4 extends javax.swing.JFrame {

    /**
     * Creates new form p4
     */
    public p4() {
        this.glo = 0;
        this.temp=0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_PKG_IDT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_PKG_TT = new javax.swing.JTextField();
        jTextField_PKG_ADD = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jTextField_PKG_GSTIN = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_PKG_T = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField_PKG_LD = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField_PKG_NTV = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField_PKG_CGST = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField_PKG_SGST = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField_PKG_IGST = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jButton_metermade = new javax.swing.JButton();
        jButton_metermade1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_PKG_MS = new javax.swing.JTextField();
        jTextField_PKG_INO = new javax.swing.JTextField();
        jButton_metermade2 = new javax.swing.JButton();
        jButton_metermade3 = new javax.swing.JButton();
        jTextField_PKG_USEDMTR = new javax.swing.JTextField();
        jTextField_PKG_TVS2 = new javax.swing.JTextField();
        jTextField_PKG_TVS3 = new javax.swing.JTextField();
        jButton_metermade_sgst = new javax.swing.JButton();
        jButton_metermade5 = new javax.swing.JButton();
        jButton_metermade_igst = new javax.swing.JButton();
        jButton_push_cgst = new javax.swing.JButton();
        jTextField_PKG_TVS = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(940, 698));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TAX ON REVERSE CHARGE -");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(500, 90, 200, 20);
        jPanel1.add(jTextField_PKG_IDT);
        jTextField_PKG_IDT.setBounds(620, 50, 250, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TOTAL BILL AMOUNT      -");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(550, 580, 200, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GSTIN -");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 90, 70, 20);
        jPanel1.add(jTextField_PKG_TT);
        jTextField_PKG_TT.setBounds(750, 580, 130, 30);
        jPanel1.add(jTextField_PKG_ADD);
        jTextField_PKG_ADD.setBounds(110, 50, 350, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("M/S -");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 10, 40, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("INVOICE NO     - ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(500, 10, 140, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("INVOICE DATE - ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(500, 50, 130, 20);

        jCheckBox1.setText("NO");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(780, 90, 50, 23);

        jCheckBox2.setText("YES");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(720, 90, 50, 23);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText(" (3) Interest will be charged at the rate of Rs. 1.5% P.M (4) E. & O.E");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(20, 570, 480, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("TERMS: (1) Money of bill to be paid at jetpur on demand. (2) goods forwarded on your account & risk");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(20, 550, 510, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TOT SLIPS", "PKG SLIP NO.", "FRESH ", "DAMAGE", "TOT PCS.", "TOTAL MTS.", "RATE", "AMOUNT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 860, 190);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" ADDRESS -");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 50, 100, 20);
        jPanel1.add(jTextField_PKG_GSTIN);
        jTextField_PKG_GSTIN.setBounds(110, 90, 350, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DENA BANK - JETPUR.   A/C.  063013031209,  RTGS : NKDN0310630");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 420, 510, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TOTAL VALUE OF SUPPLY -");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(550, 340, 200, 20);
        jPanel1.add(jTextField_PKG_T);
        jTextField_PKG_T.setBounds(590, 530, 40, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("LESS DISCOUNT %           - ");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(550, 380, 200, 20);
        jPanel1.add(jTextField_PKG_LD);
        jTextField_PKG_LD.setBounds(750, 380, 130, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("NET TAXABLE VALUE       - ");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(550, 420, 200, 20);
        jPanel1.add(jTextField_PKG_NTV);
        jTextField_PKG_NTV.setBounds(750, 420, 130, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CGST            %                   -");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(550, 460, 200, 20);
        jPanel1.add(jTextField_PKG_CGST);
        jTextField_PKG_CGST.setBounds(750, 460, 130, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("SGST            %                   -");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(550, 500, 200, 20);
        jPanel1.add(jTextField_PKG_SGST);
        jTextField_PKG_SGST.setBounds(750, 500, 130, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("PARTNER");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(380, 510, 70, 20);
        jPanel1.add(jTextField_PKG_IGST);
        jTextField_PKG_IGST.setBounds(750, 540, 130, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("TOTAL UNUSED MTR =                   -                   =");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(20, 340, 340, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("HDFC BANK - JETPUR.   A/C.  50200012115380,  IFSC : HDFC0000565");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(20, 380, 510, 20);

        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(300, 460, 230, 80);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("IGST            %                    -");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(550, 540, 200, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("COMMON SEAL ");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(80, 510, 120, 20);

        jSeparator2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(20, 550, 510, 50);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("FOR,SUNNY PRINT");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(350, 470, 150, 20);

        jSeparator3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(20, 460, 230, 80);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("COMMON SEAL ");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(80, 510, 120, 20);

        jButton_metermade.setBackground(new java.awt.Color(204, 204, 204));
        jButton_metermade.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButton_metermade.setText("m");
        jButton_metermade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_metermadeActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_metermade);
        jButton_metermade.setBounds(840, 90, 55, 30);

        jButton_metermade1.setBackground(new java.awt.Color(204, 204, 204));
        jButton_metermade1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButton_metermade1.setText("FINISH LOT");
        jButton_metermade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_metermade1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_metermade1);
        jButton_metermade1.setBounds(757, 640, 173, 39);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 102));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(910, 0, 25, 44);
        jPanel1.add(jTextField_PKG_MS);
        jTextField_PKG_MS.setBounds(110, 10, 350, 30);

        jTextField_PKG_INO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PKG_INOActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_PKG_INO);
        jTextField_PKG_INO.setBounds(620, 10, 250, 30);

        jButton_metermade2.setBackground(new java.awt.Color(204, 204, 204));
        jButton_metermade2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButton_metermade2.setText("PRINT");
        jButton_metermade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_metermade2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_metermade2);
        jButton_metermade2.setBounds(640, 640, 107, 39);

        jButton_metermade3.setBackground(new java.awt.Color(204, 204, 204));
        jButton_metermade3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButton_metermade3.setText("BACK");
        jButton_metermade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_metermade3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_metermade3);
        jButton_metermade3.setBounds(530, 640, 99, 39);
        jPanel1.add(jTextField_PKG_USEDMTR);
        jTextField_PKG_USEDMTR.setBounds(360, 330, 130, 30);
        jPanel1.add(jTextField_PKG_TVS2);
        jTextField_PKG_TVS2.setBounds(590, 450, 40, 30);
        jPanel1.add(jTextField_PKG_TVS3);
        jTextField_PKG_TVS3.setBounds(590, 490, 40, 30);

        jButton_metermade_sgst.setBackground(new java.awt.Color(204, 204, 204));
        jButton_metermade_sgst.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButton_metermade_sgst.setText("s");
        jButton_metermade_sgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_metermade_sgstActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_metermade_sgst);
        jButton_metermade_sgst.setBounds(890, 500, 30, 30);

        jButton_metermade5.setBackground(new java.awt.Color(204, 204, 204));
        jButton_metermade5.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButton_metermade5.setText("s");
        jButton_metermade5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_metermade5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_metermade5);
        jButton_metermade5.setBounds(890, 380, 30, 30);

        jButton_metermade_igst.setBackground(new java.awt.Color(204, 204, 204));
        jButton_metermade_igst.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButton_metermade_igst.setText("s");
        jButton_metermade_igst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_metermade_igstActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_metermade_igst);
        jButton_metermade_igst.setBounds(890, 540, 50, 20);

        jButton_push_cgst.setBackground(new java.awt.Color(204, 204, 204));
        jButton_push_cgst.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jButton_push_cgst.setText("s");
        jButton_push_cgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_push_cgstActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_push_cgst);
        jButton_push_cgst.setBounds(890, 460, 30, 30);

        jTextField_PKG_TVS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PKG_TVSActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_PKG_TVS);
        jTextField_PKG_TVS.setBounds(750, 340, 130, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(270, 330, 59, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(190, 330, 59, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1144, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed
public  Connection connect() throws Exception
    {  
        Connection con;
        con = null;
        Class.forName("org.apache.derby.jdbc.ClientDriver");
        String url="jdbc:derby://localhost:1527/job_db";
        con = DriverManager.getConnection(url,"root","root");
        if(con!=null)
        {
            System.out.println("connected");
        }
        return con;
    }
    public double LESS_DISCO;
    public double glo,temp;  

    /**
     *
     */
    public String s,totmtr;
    public boolean MTR,MTR5;
    public double TOTMTR_5,TOTMTR_5_5,flag_v,final_tot_mtr,used_mtr;
    /**
     *
     */
         
   javaconnect obj = new javaconnect();

    private void jButton_metermadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_metermadeActionPerformed
        // TODO add your handling code here:
        int invo_id = Integer.parseInt(jTextField_PKG_INO.getText());
        
       
        try {
        String sql = "Select * from PARTY_DETAIL where PARTY_INVO_NO="+invo_id+"";
        
        PreparedStatement pst ;
        
        ResultSet rs ;
        
            
        Connection conn  ;
        conn = connect();
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
                String name = rs.getString("PARTY_NAME");
                String gst = rs.getString("PARTY_GSTIN");
                String add = rs.getString("PARTY_ADD");
                totmtr = rs.getString("PARTY_REC_MTR");
                java.sql.Date date = rs.getDate("PART_ORDER_DATE");
                jTextField_PKG_MS.setText(name);
                jTextField_PKG_ADD.setText(add);
                jTextField_PKG_GSTIN.setText(gst);
                
                jTextField_PKG_IDT.setText(date.toString());
            } 
        } catch (SQLException ex) {
            Logger.getLogger(p3.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(p3.class.getName()).log(Level.SEVERE, null, ex);
        }
        int slp=1;
        try{
            String sql_pkg = "Select * from PKG_SLIP where INVO_NO="+invo_id+"";
            PreparedStatement tsp ;
            ResultSet sr ;
            Connection conn  ;
            conn = connect();
            tsp=conn.prepareStatement(sql_pkg);
            sr=tsp.executeQuery();
            while(sr.next())
            {
            int bale_no=sr.getInt("BALE_NO");
            double fresh = sr.getDouble("FRESH");
            double damage = sr.getDouble("DAMAGE");
            double totpis;
                totpis = sr.getInt("TOT_PIECES");
            MTR = sr.getBoolean("MTS_5");
            MTR5 = sr.getBoolean("MTS_5_5");
            if(MTR==true)
            {
                TOTMTR_5=5*totpis;
            }else{
                TOTMTR_5_5=5.50*totpis;
            }
            if(TOTMTR_5 == 0.0)
            {
                flag_v=TOTMTR_5_5;
            }
            else
            {
                flag_v=TOTMTR_5;
            }
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            temp=totpis*28.0;
            model.addRow(new Object[]{slp,bale_no,fresh,damage,totpis,flag_v,28,temp});
            
            slp++;
            glo=glo+temp;
           
                s = Double.toString(glo);
            jTextField_PKG_TVS.setText(s);
            }
           // System.out.println("tot 5 mtr = "+TOTMTR_5);
           // System.out.println("tot 5_5 mtr = "+TOTMTR_5_5);
            
           final_tot_mtr+=flag_v;
           jTextField2.setText(totmtr);
           jTextField1.setText(Double.toString(flag_v));
           double tmptmp=Double.parseDouble(totmtr);
           used_mtr=tmptmp-flag_v;
           // System.out.println(used_mtr);
           jTextField_PKG_USEDMTR.setText(Double.toString(used_mtr));
           
        }
        catch(Exception e){
           Logger.getLogger(p3.class.getName()).log(Level.SEVERE, null, e);
        }
        
        /*obj.setTOT_VAL_SUPPLY(glo);
        try {
            obj.insert();
        } catch (Exception ex) {
            Logger.getLogger(p4.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        
        
    }//GEN-LAST:event_jButton_metermadeActionPerformed

    private void jButton_metermade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_metermade1ActionPerformed
        // TODO add your handling code here:finihsottrytfyyt
        
        
        
         try {
           
        } catch (Exception ex) {
            Logger.getLogger(p4.class.getName()).log(Level.SEVERE, null, ex);
        }
         
       try {
           PreparedStatement ps;
           String sql;
           Connection con  = connect();
           int invo_id = Integer.parseInt(jTextField_PKG_INO.getText());
           sql="UPDATE PARTY_DETAIL SET TOT_VAL_SUPPLY=?,LESS_DISCOUNT_TKA=?,LESS_DISCOUNT_INR=?,CGST_TKA=?,CGST_INR=?,SGST_TKA=?,SGST_INR=?,IGST_TKA=?,IGST_INR=?,PARTY_TOT_BILL_RUPEE=?,PARTY_USED_MTR=? where PARTY_INVO_NO="+invo_id+"";
        
            ps=con.prepareStatement(sql);
            
        ps.setDouble(1, Double.parseDouble(jTextField_PKG_TVS.getText()));
        ps.setDouble(2,Double.parseDouble(jTextField_PKG_LD.getText()));
        ps.setDouble(3, Double.parseDouble(jTextField_PKG_NTV.getText()));
        ps.setDouble(4, Double.parseDouble(jTextField_PKG_TVS2.getText()));
        ps.setDouble(5, Double.parseDouble(jTextField_PKG_CGST.getText()));
        ps.setDouble(6, Double.parseDouble(jTextField_PKG_TVS3.getText()));
        ps.setDouble(7, Double.parseDouble(jTextField_PKG_SGST.getText()));
        ps.setDouble(8, Double.parseDouble(jTextField_PKG_T.getText()));
        ps.setDouble(9, Double.parseDouble(jTextField_PKG_IGST.getText()));
        ps.setDouble(10, Double.parseDouble(jTextField_PKG_TT.getText()));
        ps.setDouble(11, Double.parseDouble(jTextField_PKG_USEDMTR.getText()));
        //ps.executeUpdate();
          // System.out.println("db update succesfully");
          int rowsUpdated = ps.executeUpdate();
if (rowsUpdated > 0) {
    System.out.println("An existing user was updated successfully!");
}
        } catch (SQLException ex) {
            Logger.getLogger(p4.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(p4.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton_metermade1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton_metermade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_metermade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_metermade2ActionPerformed

    private void jButton_metermade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_metermade3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        _P1 sp=new _P1();
        sp.setVisible(true);
    }//GEN-LAST:event_jButton_metermade3ActionPerformed
public String gvar,gvar1,CGST,IGST,SGST;

    private void jButton_metermade_sgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_metermade_sgstActionPerformed
        // TODO add your handling code here:
        NumberFormat nf = NumberFormat.getInstance();
        nf.setMaximumFractionDigits(2);            
        nf.setGroupingUsed(false);
        gvar=jTextField_PKG_TVS3.getText();
        double ldt,tmp,tmp1;
        tmp=Double.parseDouble(CGST);
        tmp1=tmp;
        ldt = Double.parseDouble(gvar);
        tmp = (tmp / 100)*ldt;
        tmp1=tmp1-tmp;
        String.format(".2f",tmp1);
        SGST = Double.toString(tmp1);    
        
        jTextField_PKG_SGST.setText(SGST);
       /* obj.setSGST_TKA(ldt);
        obj.setSGST_INR(tmp1);
        try {
            obj.insert();
        } catch (Exception ex) {
            Logger.getLogger(p4.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButton_metermade_sgstActionPerformed

    /**
     *
     */
    public String ldc,got_lnv,NTV;
    private void jButton_metermade5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_metermade5ActionPerformed
        // TODO add your handling code here:
       ldc = jTextField_PKG_LD.getText();
       double ldt,tmp;
       tmp=glo;
       ldt = Double.parseDouble(ldc);
       glo = (glo / 100)*ldt;
       tmp=tmp-glo;
       NTV = Double.toString(tmp);       
       jTextField_PKG_NTV.setText(NTV);
      // obj.setLESS_DISCOUNT_TKA(ldt);
      // obj.setLESS_DISCOUNT_INR(tmp);
      /*  try {
            obj.insert();
        } catch (Exception ex) {
            Logger.getLogger(p4.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButton_metermade5ActionPerformed
    public String ldi;
    private void jButton_metermade_igstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_metermade_igstActionPerformed
        // TODO add your handling code here:]
        
        
        
        ldi=jTextField_PKG_T.getText();
        double ldt,tmp,old_value,ldit;
        old_value = Double.parseDouble(SGST);
        tmp=old_value;
        ldit = Double.parseDouble(ldi);
        old_value = (old_value / 100)*ldit;
        tmp=tmp-old_value;
        IGST = Double.toString(tmp);       
        jTextField_PKG_IGST.setText(IGST);
        jTextField_PKG_TT.setText(IGST);
       // obj.setIGST_TKA(ldit);
        //obj.setIGST_INR(tmp);
        //obj.setPARTY_TOT_BILL_RUPEE(tmp);
      
        
        
    }//GEN-LAST:event_jButton_metermade_igstActionPerformed

    private void jButton_push_cgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_push_cgstActionPerformed
        // TODO add your handling code here:
       got_lnv = jTextField_PKG_TVS2.getText();//takka
       double got_inr,ld_int,temp1,got_lnv_d;
        got_lnv_d = Double.parseDouble(got_lnv);//tkka
        System.out.println(got_lnv_d);
        System.out.println(NTV);
        got_inr = Double.parseDouble(NTV);//inr
        temp1=got_inr;
        got_inr = ((got_inr / 100)*got_lnv_d);
          System.out.println("gdivide");
        System.out.println(got_inr);
       temp1=temp1-got_inr;
       System.out.println(temp1);
       CGST = Double.toString(temp1);       
      jTextField_PKG_CGST.setText(CGST);
      //obj.setCGST_TKA(got_lnv_d);
      //obj.setCGST_INR(temp1);
       /* try {
            obj.insert();
        } catch (Exception ex) {
            Logger.getLogger(p4.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButton_push_cgstActionPerformed

    private void jTextField_PKG_INOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PKG_INOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PKG_INOActionPerformed

    private void jTextField_PKG_TVSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PKG_TVSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PKG_TVSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_metermade;
    private javax.swing.JButton jButton_metermade1;
    private javax.swing.JButton jButton_metermade2;
    private javax.swing.JButton jButton_metermade3;
    private javax.swing.JButton jButton_metermade5;
    private javax.swing.JButton jButton_metermade_igst;
    private javax.swing.JButton jButton_metermade_sgst;
    private javax.swing.JButton jButton_push_cgst;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_PKG_ADD;
    private javax.swing.JTextField jTextField_PKG_CGST;
    private javax.swing.JTextField jTextField_PKG_GSTIN;
    private javax.swing.JTextField jTextField_PKG_IDT;
    private javax.swing.JTextField jTextField_PKG_IGST;
    private javax.swing.JTextField jTextField_PKG_INO;
    private javax.swing.JTextField jTextField_PKG_LD;
    private javax.swing.JTextField jTextField_PKG_MS;
    private javax.swing.JTextField jTextField_PKG_NTV;
    private javax.swing.JTextField jTextField_PKG_SGST;
    private javax.swing.JTextField jTextField_PKG_T;
    private javax.swing.JTextField jTextField_PKG_TT;
    private javax.swing.JTextField jTextField_PKG_TVS;
    private javax.swing.JTextField jTextField_PKG_TVS2;
    private javax.swing.JTextField jTextField_PKG_TVS3;
    private javax.swing.JTextField jTextField_PKG_USEDMTR;
    // End of variables declaration//GEN-END:variables

  

    
}
